name: 'hybrid'

# 姿态参数
# mass_rot: [0.4,0.4,0.4]
# stiff_rot: [4,4,4]
# desired_xi: 1.2
# damp_rot: [-1,-1,-1]

# mass_rot: [10,10,10]
# stiff_rot: [1000,1000,1000]
# damp_rot: [-125,-125,-125]
# desired_xi: 0.7


mass_rot: [0.2, 0.2, 0.2]
stiff_rot: [4, 4, 4]
damp_rot: [0.6, 0.6, 0.6]
desired_xi: 1.0


# 力控参数   
force_mass: 1   #M，质量系数越小，力控越灵敏，过小又会不稳定
force_damp: 3   #D，阻尼系数
Kp_force: 8    #P，比例系数越大，力控越灵敏
Kd_force: 0.5  #微分增益，用于改善稳定性
Ki_force: 0.2  #I ,用于消除稳态误差

#机械臂在z轴方向通过增量式PID控制，给向上的力则会向上运动，给向下的力则会向下运动，
#直到力平衡，所以可以给一个初始的向下的期望力，然后通过力控控制机械臂运动到期望位置

# 位控参数
Kp: [70,70]
Ki: [0,0]
Kd: [5,5]

# # 位控参数
# Kp_R: [7,7,7]
# Ki_R: [0,0,0]
# Kd_R: [1,1,1]




# # 位控参数
# Kp: [90,90]
# Kd: [25,25]

