# 机械臂IP
arm_ip: 114

# 控制器
controller: ['/home/jsfb/jsfb_ws/MassageRobot_huiling/Massage/MassageControl/config/admittance.yaml',
              '/home/jsfb/jsfb_ws/MassageRobot_huiling/Massage/MassageControl/config/hybrid.yaml',
              '/home/jsfb/jsfb_ws/MassageRobot_huiling/Massage/MassageControl/config/position.yaml',
              '/home/jsfb/jsfb_ws/MassageRobot_huiling/Massage/MassageControl/config/admithybrid.yaml',
              '/home/jsfb/jsfb_ws/MassageRobot_huiling/Massage/MassageControl/config/hybridPid.yaml',]


# # 控制器
# controller: ['MassageControl/config/admittance.yaml',
#               'MassageControl/config/hybrid.yaml',
#               'MassageControl/config/position.yaml',
#               'MassageControl/config/admithybrid.yaml',
#               'MassageControl/config/hybridPid.yaml',]
      
# 按摩头文件夹
massage_head_dir: '/home/jsfb/jsfb_ws/global_config/massage_head'

# control_rate: 60 #机械臂控制频率要比读取状态频率低
# sensor_rate:  250  #力传感器读取频率固定250hz
# arm_rate : 50   #机械臂读取状态频率最大20hz   #最大50hz先试试
# command_rate: 90  #30



control_rate: 110     # dt = 0.01s  后续考虑应该调整到20hz
xy_control_rate: 100
sensor_rate: 250      
arm_rate: 100         # 提高到100Hz
command_rate: 100     